"""criar tabelas iniciais

Revision ID: 3a05db1c7b1e
Revises: 
Create Date: 2025-04-05 20:54:22.093690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a05db1c7b1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('feed_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_podcast'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rel_podcast_usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'podcast_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_podcast_usuario')
    op.drop_table('usuario')
    op.drop_table('podcast')
    # ### end Alembic commands ###
